apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: user-svc-destination
spec:
  host: user-svc-svc
  subsets:
    - name: v1
      labels:
        version: v1.4
    - name: v2
      labels:
        version: v1.5
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-svc-rule
spec:
  hosts:
    - "user-svc-svc"
  http:
    - route:
        - destination:
            host: user-svc-svc
            subset: v1
          weight: 75
        - destination:
            host: user-svc-svc
            subset: v2
          weight: 25